### ISSUE TITLE
Mini White Bulbs appear as colored bulbs in Home App UI

### ISSUE THREAD

**Issue by 7RDR7** [calvarium/homebridge-lifx-plugin#1]
Thank-you for creating this plugin!! Native LIFX HomeKit was driving me crazy...very flaky..... I've only had the plugin for a day, but it's already solved all of my issues!

**Describe The Bug:**
 Low priority issue. The LIFX Mini White bulbs appear as colored bulbs within the Home app. All other bulbs and strips appear and operate as they should (color). 

**To Reproduce:**
 Not required

**Expected behavior:**
 LIFZ Mini White bulbs should appear as a non-color dimmer, with no color selection options.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
 {
            "name": "Lifx Plugin",
            "duration": 0,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "debug": false,
            "autoDiscover": true,
            "platform": "LifxPlugin"
        }

**Screenshots:**

![IMG_6162](https://user-images.githubusercontent.com/69693185/145736684-59154c13-f81d-466b-9498-4efbf355c431.PNG)
![IMG_6161](https://user-images.githubusercontent.com/69693185/145736692-601dda95-03d2-40ed-b5ef-d0f18d4d66e1.PNG)

**Environment:**

* **Plugin Version**: v0.1.9
* **Homebridge Version**:  v1.3.8
* **Node.js Version**:  v16.13.1
* **NPM Version**:  v8.3.0
* **Operating System**:  macOS Big Sur

**Comment by calvarium** [comment]
Hello 7RDR7,

thank you for your feedback and your kind words. I am very happy that you like the plugin. 
The latest update (0.1.10) should now show your LIFX Mini White bulbs as such!

I'm curious to hear your feedback, as I don't have any bulbs in use without colors myself.

**Comment by 7RDR7** [comment]
Hello Calvarium,
Thank-you for the quick turnaround. I installed the update and the light now appears as a non-color light, but with temperature adjustment. The Mini White is fixed @ 2700K, so temperature adjustment is not supported, otherwise it works fine. LIFX does support temperature adjustment on their white candle lights, but I don't have any of those. Again, a low priority request. My other 23 color bulbs/strips are are working great! I just appreciate you building this plugin. Thanks again!

**Comment by calvarium** [comment]
Hi 7RDR7,
thank you for making it possible to make this plugin even better.
The latest update (0.1.11) should fulfill all your wishes, your mini's should be displayed correctly now.

**Comment by 7RDR7** [comment]
Perfect! Loaded and working. Thank-you! Issue closed.
