### ISSUE TITLE
Support for Adaptive Lighting

### ISSUE THREAD

**Issue by joelrichards** [calvarium/homebridge-lifx-plugin#11]
**Is your feature request related to a problem? Please describe:**
While the LIFX app supports "Day-to-Dusk" I really prefer to keep all of my configuration/interaction in the Home app. I was very excited when Apple announced Adaptive Lighting but LIFX seems never to implement it. Can it be done through your bridge plugin? If so is there a way to support you to make that happen?

**Comment by calvarium** [comment]
Hello @joelrichards,

I am happy to announce that the plugin in its latest version (0.2.0) now supports adaptive lighting.

**Comment by joelrichards** [comment]
Thank you, thank you, thank you! So far this works great. So seamless! Thank you!

**Comment by calvarium** [comment]
Thank you for your support and this great idea! Hope you have a lot of fun with your bulbs
