### ISSUE TITLE
Lifx White 800 not working

### ISSUE THREAD

**Issue by thefern69** [calvarium/homebridge-lifx-plugin#15]
**Describe The Bug:**

It looks like the Lifx white 800 is not supported

**To Reproduce:**

Have set up adaptive lighting in the home app. No colour changing. Tried to change colour manually in the app and no changing either. Lifx app still changes colour. 

**Expected behavior:**

Expect to see colour change over the day

**Logs:**

```
DEBUG - 58000014f35ce128d073d510844600004c49465856320054e87248d87b80da166b00000000000000ffff64190000ffff46616d696c7920526f6f6d204c616d70000000000000000000000000000000000000000000000000 from 192.168.1.249
DEBUG - 24000034f35ce12800000000000000000000000000000054000000000000000002000000 to 255.255.255.255
DEBUG - 29000014f35ce128d073d510844600004c49465856320054e8caa9f07c80da1603000000017cdd0000 from 192.168.1.249
DEBUG - 29000014f35ce128d073d510844600004c49465856320054e81292f27c80da1603000000057cdd0000 from 192.168.1.249
DEBUG - 24000014f35ce128d073d510844600000000000000000055000000000000000065000000 to 192.168.1.249
DEBUG - 58000014f35ce128d073d510844600004c49465856320055e8644e027d80da166b00000000000000ffff64190000ffff46616d696c7920526f6f6d204c616d70000000000000000000000000000000000000000000000000 from 192.168.1.249 ```

**Plugin Config:**

```json

{
    "name": "Lifx Plugin",
    "duration": 0,
    "brightnessDuration": 500,
    "colorDuration": 500,
    "default": "0.0.0.0",
    "broadcast": "255.255.255.255",
    "lightOfflineTolerance": 3,
    "messageHandlerTimeout": 45000,
    "resendPacketDelay": 150,
    "resendMaxTimes": 3,
    "updates": true,
    "debug": false,
    "autoDiscover": true,
    "platform": "LifxPlugin"
}

```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.2.2
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.14.0
* **NPM Version**:  8.3.1
* **Operating System**: macOS

**Comment by calvarium** [comment]
Hi, 
could you help me a little further to understand exactly where the problem lies. 
A screenshot of this would already help me a lot:
<img width="200" alt="adaptive lighting" src="https://user-images.githubusercontent.com/94163719/157392187-1238c8a2-13bc-4726-964c-00a6a647ef1d.PNG">

**Comment by thefern69** [comment]
![Library - 1 of 1 (1)](https://user-images.githubusercontent.com/62212846/157404496-7d5c4249-37e3-4237-9756-e8bb668ccf5f.jpeg)

How's this?

**Comment by thefern69** [comment]
I have the original box, Model BUL-11-A19e27-W. They are old, pre-homekit. Lifx app says firmware is up to date. and is v1.22 on the lifx app. The app advanced setting has Advanced Kelvin Control off. Anything else?

**Comment by thefern69** [comment]
Oh, and to confirm, my Lifx mini cool is working absolutely fine - thanks v much.

**Comment by thefern69** [comment]
Hi, can I provide any more information?

**Comment by calvarium** [comment]
Hi @thefern69,

still having this issue with the current version of the plugin?
Let me get this straight. You can't change the color temperature in the home app? Only brightness? Is that correct?

**Comment by thefern69** [comment]
@calvarium apologies for the delay in replying. Yes, it looks like it is working fine. Thanks v much for your help and for the plugin - keep up the good work.
