### ISSUE TITLE
LIFX bulbs randomly dim to 0% but remain on when using plugin

### ISSUE THREAD

**Issue by JeffMorrison15** [calvarium/homebridge-lifx-plugin#16]
**Describe The Bug:**
After some time, my bulbs start to dim themselves one by one -- no reason to it but if I remove the homebridge-lifx plugin and add them manually to HomeKit -- no issues at all. I wanted to try out adaptive lighting with this plugin but the randomly dimming to 0% of the bulbs is maddening so I have to remove it.

**To Reproduce:**
Anything -- Adding bulbs via discovery -- same issue
Adding bulbs manually -- same issue.

I am a network administrator and have a full Cisco Meraki stack and I can help gather packet captures from anything on the network with the tools this gear comes with. 

**Expected behavior:**
Bulb is turned on and then the bulb stays turned on and at that brightness until I change the brightness or turn it off. Bulbs should not be dimming themselves on their own.

**Logs:**

[homebridge.log.txt](https://github.com/calvarium/homebridge-lifx-plugin/files/8311815/homebridge.log.txt)

**Plugin Config:**

{
    "name": "Lifx Plugin",
    "duration": 0,
    "brightnessDuration": 300,
    "colorDuration": 300,
    "default": "0.0.0.0",
    "broadcast": "192.168.15.255",
    "lightOfflineTolerance": 3,
    "messageHandlerTimeout": 45000,
    "resendPacketDelay": 150,
    "resendMaxTimes": 3,
    "updates": false,
    "debug": false,
    "autoDiscover": false,
    "bulbs": [
        {
            "name": "Kitchen Table Lamp",
            "address": "192.168.15.1"
        },
        {
            "name": "Kitchen Can Bulb",
            "address": "192.168.15.2"
        },
        {
            "name": "Kitchen Can Bulb",
            "address": "192.168.15.3"
        },
        {
            "name": "Kitchen Can Bulb",
            "address": "192.168.15.4"
        },
        {
            "name": "Kitchen Can Bulb",
            "address": "192.168.15.5"
        },
        {
            "name": "Kitchen Sink Bulb",
            "address": "192.168.15.6"
        },
        {
            "name": "Living Room Lamp Bulb",
            "address": "192.168.15.7"
        },
        {
            "name": "Living Room Lamp Bulb",
            "address": "192.168.15.8"
        },
        {
            "name": "Living Room Lamp Bulb",
            "address": "192.168.15.9"
        },
        {
            "name": "Front Room Chair Lamp",
            "address": "192.168.15.10"
        },
        {
            "name": "Front Room Chandelier Bulb",
            "address": "192.168.15.11"
        },
        {
            "name": "Front Room Chandelier Bulb",
            "address": "192.168.15.12"
        },
        {
            "name": "Front Room Chandelier Bulb",
            "address": "192.168.15.13"
        },
        {
            "name": "Front Room Chandelier Bulb",
            "address": "192.168.15.14"
        },
        {
            "name": "Front Room Chandelier Bulb",
            "address": "192.168.15.15"
        },
        {
            "name": "Front Door Bulb",
            "address": "192.168.15.16"
        },
        {
            "name": "Front Door Bulb",
            "address": "192.168.15.17"
        },
        {
            "name": "Front Door Bulb",
            "address": "192.168.15.18"
        },
        {
            "name": "Living Room Ceiling Fan Bulb",
            "address": "192.168.15.19"
        },
        {
            "name": "Living Room Ceiling Fan Bulb",
            "address": "192.168.15.20"
        },
        {
            "name": "Living Room Ceiling Fan Bulb",
            "address": "192.168.15.21"
        },
        {
            "name": "Master Bedroom Ceiling Fan Bulb",
            "address": "192.168.15.22"
        },
        {
            "name": "Master Bedroom Ceiling Fan Bulb",
            "address": "192.168.15.23"
        },
        {
            "name": "Master Bedroom Ceiling Fan Bulb",
            "address": "192.168.15.24"
        },
        {
            "name": "Master Bedroom Lamp Bulb",
            "address": "192.168.15.25"
        },
        {
            "name": "Master Bedroom Lamp Bulb",
            "address": "192.168.15.26"
        },
        {
            "name": "Master Bath Bulb",
            "address": "192.168.15.27"
        },
        {
            "name": "Master Bath Bulb",
            "address": "192.168.15.28"
        },
        {
            "name": "Master Bath Bulb",
            "address": "192.168.15.29"
        },
        {
            "name": "Master Bath Bulb",
            "address": "192.168.15.30"
        },
        {
            "name": "Master Bath Bulb",
            "address": "192.168.15.31"
        },
        {
            "name": "Master Bath Bulb",
            "address": "192.168.15.32"
        },
        {
            "name": "Hallway Light",
            "address": "192.168.15.33"
        }
    ],
    "_bridge": {
        "username": "0E:A8:99:1C:9B:78",
        "port": 30938
    },
    "platform": "LifxPlugin"
}

**Screenshots:**
![Screen Shot 2022-03-20 at 10 23 20 AM](https://user-images.githubusercontent.com/101989451/159174600-a249d87a-4318-4d6d-98c2-64c571f4b6b3.png)

**Environment:**
MacOS Monterey 12.3 -- Homebridge.io runs on this.
Cisco Meraki -- MX, MS, MR Full stack
X2 MR36 -- not overwhelmed by all the bulbs at all, I use these with customers that have much higher density.

* **Plugin Version**:
homebridge-lifx-plugin v0.2.2

* **Homebridge Version**: 

* **Node.js Version**: 
v16.4.0 ---> Updating to 1v6.4.2 NOW!
I did not realize I was out of date, I installed this yesterday
If this s a known issue the v16.4.0 please let me know and we can close this

* **NPM Version**: 
8.3.1 --> Upgrading to v8.5.0 NOW!
If this s a known issue the v16.4.0 please let me know and we can close this

* **Operating System**: 
MacOS 12.3

**Comment by JeffMorrison15** [comment]
I set the default route directly to my home bridge servers interface and updated to the latest version of nodeJS and NPM. 
So far I have not had the issue return...

**Comment by JeffMorrison15** [comment]
Ahhh never mind -- still an issue.
I think it just took a moment to kick in after I restarted the home bridge when updating nodejs and setting default route.

![Screen Shot 2022-03-20 at 11 10 27 AM](https://user-images.githubusercontent.com/101989451/159176408-b10489dd-30d2-4ecc-8dc7-f3b311224a5b.png)

**Comment by JeffMorrison15** [comment]
Any updates on this?

**Comment by calvarium** [comment]
Hi @JeffMorrison15,

Sorry for the long wait. I have tried to understand what could be causing this problem, however, I am currently asking myself one question: Do the bulbs physically dim to 0% or is it just shown to you in the home app?

I can only think of one way that this problem can occur at the moment and that is that packets are not being transmitted correctly over your network. Every few seconds the status of the bulbs is queried and if no packet comes back the status of the bulb is set to 0. This only happens in the display. Do you have any idea what could cause this behavior in your network?
