### ISSUE TITLE
LIFXZ Strip not working correctly on adaptive lighting

### ISSUE THREAD

**Issue by retroaces** [calvarium/homebridge-lifx-plugin#18]
**Describe The Bug:**
LifxZ strips with 1 extension are going into 9000k when adaptive lighting is selected inside homekit. All other lifx lights are working just fine, which include LIFX bulbs.

**To Reproduce:**
Each time I turn on adaptive lighting.

**Expected behavior:**
Ideally the bulbs would match the same lighting temperature as the room they are in, but at least be close to the same kelvin value.

**Logs:**

which part of the logs are you needing?

**Plugin Config:**

     "name": "Lifx Plugin",
            "duration": 4000,
            "brightnessDuration": 900,
            "colorDuration": 900,
            "default": "0.0.0.0",
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "updates": true,
            "debug": false,
            "autoDiscover": true,
            "platform": "LifxPlugin"

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.4.1
* **Node.js Version**: 18.2.0
* **NPM Version**: not sure where to find this
* **Operating System**: macOS

**Comment by calvarium** [comment]
Hi @retroaces,

do I understand correctly that no matter when you activate adaptive lighting, the strip is set to 9000K?

**Comment by huw** [comment]
Just to confirm, I’m seeing this bug also and the described behaviour is correct. It’s always at the same bright blue colour, regardless of time of day or set brightness level.

**Comment by eramdam** [comment]
I'm seeing the same behavior as well with LIFX Z strips.

**Comment by eramdam** [comment]
I think I identified the issue. The temperatures range for LIFX Z devices seems to be wrong. They're defined as 2500-9000, whereas the LIFX iOS app lets you set a minimum of 1500K.

![IMG_3259](https://user-images.githubusercontent.com/1409924/204208861-0177fd3a-e08e-4db8-900f-c76a891d2ae7.PNG)

I patched `products.json` to reflect the correct range for LIFX Z devices and this fixes the issue. I'll open a PR 🙇

**Comment by calvarium** [comment]
v0.2.4 addresses this bug
After updating you should be able to use the full range of your bulbs

**Comment by eramdam** [comment]
> v0.2.4 addresses this bug After updating you should be able to use the full range of your bulbs

Will test and report back!

**Comment by eramdam** [comment]
Seems like 0.2.4 fixed it 🎉

**Comment by calvarium** [comment]
Glad to hear that
