### ISSUE TITLE
LIFX Mini Day & Dusk bulbs appear as coloured bulbs 

### ISSUE THREAD

**Issue by L0T8** [calvarium/homebridge-lifx-plugin#3]
I want to say thank you for the plugin you created. It saves me from having headaches with the official HomeKit version. I'm currently facing this minor nuisance with LIFX Mini Day & Dusk bulbs. Also, I have LIFX Smart Switch 4 Button and I don't think this switch should appear in the Homekit since none of the buttons are connected to dumb bulbs.

**Describe The Bug:**

Displaying RGB colour options in the accessory menu of LIFX Mini Day & Dusk bulb. This bulb has a huge warm-cool white range (1,500K-6,500K). 

**To Reproduce:**

Open accessory menu normally

**Expected behavior:**

Should only display dimmer control and temperature colours, instead of RGB colours. As shown in the attached screenshot of the official HomeKit UI below.

**Logs:**

```
N/A
```

**Plugin Config:**

```json
        {
            "name": "LIFX Plugin",
            "duration": 0,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "debug": false,
            "autoDiscover": true,
            "platform": "LifxPlugin"
        },
```

**Screenshots:**

![officialhomekitdd](https://user-images.githubusercontent.com/4318785/146664636-b6ef1aaf-aec3-4556-bf0b-c1165c9f6c2c.png)
<br>
![homebridgedd](https://user-images.githubusercontent.com/4318785/146664634-c5da7b8b-4d9a-4767-86cc-920146b11d34.png)

**Environment:**

* **Plugin Version**: 0.1.14
* **Homebridge Version**: 1.3.8
* **Node.js Version**: 16.13.1
* **NPM Version**: 8.1.2
* **Operating System**: macOS Mojave

**Comment by calvarium** [comment]
Hi L0T8,

I'm glad you like the plugin.
With your help I was able to make it even better. Your bulbs should be properly integrated into your HomeKit in the latest update.

Additionally I added the functionality to create exceptions for your LIFX accessories. You can now add the IP or serial number of your accessories under 'Excludes' in the settings. These devices will then be ignored by the plugin and automatically removed from your HomeKit.

Thanks again for this idea. Please let me know if everything works as you imagined.

Many greetings

**Comment by L0T8** [comment]
Got all my Mini Day & Dusk bulbs working with the latest update. It's displaying the temperature colour options correctly. 
Plus, I'm able to hide the LIFX Smart Switch using its serial number only. Thank you for releasing the fix!

Just letting you know, I also have LIFX GU10 bulbs that are working properly with this plugin. You can add "LIFX Mini Day & Dusk" and "LIFX GU10" to the list in readme.md :)
