### ISSUE TITLE
Multi NIC Discovery Broadcast

### ISSUE THREAD

**Issue by andyvirus** [calvarium/homebridge-lifx-plugin#5]
I have separate IoT VLAN and User Device VLANs. My Homebridge VM has a NIC in each. Would it be possible to have your plugin broadcast from all network cards or to define in the settings of the plugin which NICs should be used for broadcast and discovery?

If I define each IP then the correct NIC is used of course and all is fine, but broadcast and Discovery is only used on one NIC not all. I ran a Wireshark on both vlans and can only see broadcasts to 255.255.255.255 on the first NIC which is not where my bulbs reside.

I have given up with LIFX Native HomeKit support. Even on a flat network its a coin toss as if these bulbs will speak hap/mdns.
I have 12 Colour Minis and 2 Z Strips (Though the Z Strips are rock solid on HAP/MDNS and behave very differently than the minis).

Hope your well!

**Comment by calvarium** [comment]
Hello andyvirus,

I can understand that you are looking for an alternative, as I had the same trouble with my bulbs and would like to help you.
First of all I would like to know if other plugins can broadcast to both NICs.
At this point it is not possible for me to distinguish which network my plugin is accessing, but you can tell the Homebridge which interfaces should be actively used.

You would find this option under "Homebridge Settings" -> "Network Interfaces". With a click on the cogwheel you can select all networks you want the Homebridge to listen to.

Let me know if I could help you with this

**Comment by andyvirus** [comment]
Hello,

I have shelly devices on one vlan, lets call it vlan 2, which is separate to the management lan (vlan1 though in reality it is not tagged) where I access home bridge and which the apple devices are also located. This seems to be working fine. LIFX bulbs are on vlan3. 

I was not aware of that setting in home bridge. all interfaces were unchecked. I have now checked all 3 interfaces and restarted but still no discovery. I have tried just selecting vlan3 Nic and still no discovery.

The only work around I have is to move the bulbs to vlan1, let them get discovered then move them to vlan3. The only issue then is I need a firewall rule as comms will be to the vlan1 interface of home bridge not 3. Not the end of the world but was just seeing if there was a lan local way instead of routing the traffic between vlans.

I will report back on how I get on with the LIFX Colour Minis (800 lumen versions as the new new ones are 1000 lumen of which I have none yet) for your compatibility table.

**Comment by calvarium** [comment]
Hi,

in the newest version (0.1.20) I have added the functionality of a default route in the advanced settings. By default the 0.0.0.0 is used, here you should now address the route on which you can reach your accessories.

Let me know if it works

**Comment by andyvirus** [comment]
Hi Calvarium,

I think that is working. I have moved all the bulbs back to vlan3, renewed IPs and all seem to be controllable. Some I won't be able to test until tomorrow but so far, all seem to be responding to control via HomeKit. I set the route to the IP of the interface of home bridge assigned to vlan3. I will test more throughly but looks like I can now discover via a specific interface.

Thankyou so much!

**Comment by calvarium** [comment]
Hi Andyvirus,

Glad to hear that it works💪 
Let me know what your further tests have shown

**Comment by andyvirus** [comment]
Short of completely removing and re-adding a bulb I think I have gone as far with my testing as is possible. All seems to be working now on the NIC I want to control the bulbs on. Thanks again! Truly this is the most feature rich LIFX plugin on Homebridge!

**Comment by calvarium** [comment]
Glad that everything works to your satisfaction and thank you for your kind words. 
If you think of any further improvements, please let me know.
