### ISSUE TITLE
Exclude devices by Serial/MAC address only

### ISSUE THREAD

**Issue by andyvirus** [calvarium/homebridge-lifx-plugin#6]
If possible, could exclusions be defined by just the MAC/Serial number as with DHCP the IP changes. I have tried with just the Serial/MAC and discovery still finds the lifx lights not desired to be added by this plugin.

Thankyou so much for your efforts with this plugin!

Also, I have tested LIFX Z Strips and both work fine via your plugin. These are the ones I was trying to exclude via exclusions but as they were discovered, tested colour, on and off... All functional via the plugin.

**Comment by calvarium** [comment]
Hi andyvirus,

an exclusion via MAC address is unfortunately not supported at the moment. However, I understand your problem that blocking an IP via DHCP is not really promising. For this case I have integrated the exclusion via the serial number of the individual bulb. 
You can find this character combination on the barcode of your freshly purchased accessories or directly in the homeapp in the settings of the bulb under the item serial number.

Let me know if you could achieve a success

**Comment by andyvirus** [comment]
Hi,

The serial and the mac address are the same, on my bulbs at-least. I have added the serial but they are still found during discovery.

**Comment by calvarium** [comment]
You're right, I wasn't aware of that until just now.
Did you specify the MAC with a "-" or just the letters? If that is the case, please try again without the "-" and in lower case without spaces like this: "a1b2c3d4e5"
I have tested it this way

Keep me up to date

**Comment by andyvirus** [comment]
I just put the serial in as it show in the app. No - or : or spaces. Ill delete both sets of HomeKit bulbs (native and via your plugin) and try again.

**Comment by calvarium** [comment]
Thanks for your feedback. This closes this issue
