### ISSUE TITLE
Phantom Updates on LIFX GU10 After Homebridge Restarts

### ISSUE THREAD

**Issue by L0T8** [calvarium/homebridge-lifx-plugin#8]
**Describe The Bug:**
Every time the Homebridge restarts, the phantom updates appear for LIFX GU10 bulbs. I have three GU10 bulbs, and they sometimes show one to three updates. They disappear on their own after one to 12 hours. The phantom update doesn't happen for other LIFX bulbs, including A19 and Day & Dusk. 

**To Reproduce:**
1. Have a LIFX GU10 bulb
2. Restart Homebridge
3. Receive a notification for the "phantom" update 

**Expected behavior:**
The phantom update should not happen for GU10 bulbs. There should be an option to disable an update check for bulb/s. Homebridge API documentation mentions Firmware Update.

**Logs:**

N/A

**Plugin Config:**

```
        {
            "name": "LIFX Plugin",
            "duration": 0,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "debug": false,
            "autoDiscover": true,
            "excludes": [
                {
                    "name": "LIFX Switch",
                    "id": "d073d5635c52"
                }
            ],
            "platform": "LifxPlugin"
        }
```

**Screenshots:**
![IMG_9BEFCF97BA11-1](https://user-images.githubusercontent.com/4318785/152276867-9e8af703-f4e8-49a8-ad81-2c0c01fc9853.jpeg)

**Environment:**

* **Plugin Version**: v0.1.20
* **Homebridge Version**: v1.4.0
* **Node.js Version**: v16.13.1
* **NPM Version**: v8.1.2
* **Operating System**: macOS Mojave

**Comment by calvarium** [comment]
Hi @L0T8,

I had the same problem with my Z Strips that are secondarily not connected to power.
In the latest update (v0.1.21) we should no longer have problems with the update function of the Homekit.
In addition, I have added the function to disable updates manually

If you have any other problems with the plugin let me know

**Comment by L0T8** [comment]
Hi @calvarium,

Thanks for the quick fix. The phantom update no longer shows up for GU10 when I restart my Homebridge

-L0T8
